### ISSUE TITLE
ActionView::Template::Error: undefined method `generate_key'

### ISSUE THREAD

**Issue by assimovt** [brainopia/backport_new_renderer#1]
For some reason I get this error when rendering a partial from the Rails console:

```
ActionView::Template::Error: undefined method `generate_key' for nil:NilClass
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/cookies.rb:453:in `initialize'
```

**Comment by assimovt** [comment]
Looks like it was a problem on my side. Works perfectly, thanks.

**Comment by bjreath** [comment]
@assimovt What did you end up doing to fix this? I ran into the same issue.

**Comment by assimovt** [comment]
@bjreath Oh, it was so long ago that I don't remember. We are on Rails 5 and no issues there.
